In [14]:

# Collection of documents (corpus)
#Phone Reviews #Research Abstracts #Facebook Comments #Twitter Tweets

Doc_1= "new home sales top forecasts"
Doc_2= "home sales rise in july"
Doc_3= "increase in home sales in july"
Doc_4= "july new home sales rise"

In [15]:
docs = [Doc_1, Doc_2, Doc_3,Doc_4 ]
docs

['new home sales top forecasts',
 'home sales rise in july',
 'increase in home sales in july',
 'july new home sales rise']

In [16]:
# Gather the set of all unique terms
unique_terms = {term for doc in docs for term in doc.split()}
unique_terms

{'forecasts', 'home', 'in', 'increase', 'july', 'new', 'rise', 'sales', 'top'}

In [17]:
# Construct a term-document matrix
# here as a Python dictionary for ease of interpretability

doc_term_matrix = {}

for term in unique_terms:
    doc_term_matrix[term] = []
    
    for doc in docs:
        if term in doc:
            doc_term_matrix[term].append(1)
        else: doc_term_matrix[term].append(0)

doc_term_matrix

{'new': [1, 0, 0, 1],
 'july': [0, 1, 1, 1],
 'sales': [1, 1, 1, 1],
 'forecasts': [1, 0, 0, 0],
 'in': [0, 1, 1, 0],
 'home': [1, 1, 1, 1],
 'top': [1, 0, 0, 0],
 'increase': [0, 0, 1, 0],
 'rise': [0, 1, 0, 1]}

In [20]:
# The query to find all documents containing "home" AND "sales"AND "july"
# Is just a bitwise AND:

import numpy as np

docs_array = np.array(docs, dtype='object')

v1 = np.array(doc_term_matrix['home'])    
v2 = np.array(doc_term_matrix['sales'])
v3 = np.array(doc_term_matrix['july'])
print(v1)
print(v2)
print(v3)
print('-------')
v = v1 & v2 & v3
print(v)

[1 1 1 1]
[1 1 1 1]
[0 1 1 1]
-------
[0 1 1 1]


In [21]:
# We can now get the matching documents from our corpus with the result
[doc for doc in v * docs_array if doc]

['home sales rise in july',
 'increase in home sales in july',
 'july new home sales rise']

In [23]:
# Bitwise OR to construct 'this' or 'that' queries.

v1 = np.array(doc_term_matrix['forecasts'])    
v2 = np.array(doc_term_matrix['rise'])

print(v1)
print(v2)
print('-------')
v = v1 | v2
print(v)

[1 0 0 0]
[0 1 0 1]
-------
[1 1 0 1]


In [24]:
# We can now get the matching documents from our corpus with the result
[doc for doc in v * docs_array if doc]

['home sales rise in july',
 'increase in home sales in july',
 'july new home sales rise']